### ISSUE TITLE
Error: Missing required param: email

### ISSUE THREAD

**Issue by symbianm** [h2non/youtube-video-api#12]
I have an error "Missing required param: email" if I init youtube in this way:

```
 var youtube = Youtube({
        video: {
            part: 'status,snippet'
        },
        email: 'some email',
        password: 'some pass'
    });
```

If you fix lines 117 and 118 in index.js file to these, it will work

```
email: this.opts.email || process.env.GOOGLE_LOGIN_EMAIL,
password: this.opts.password || process.env.GOOGLE_LOGIN_PASSWORD,
```

**Comment by h2non** [comment]
Oh, great! It was was fault, since I'm using it as environment variable. Will merge the PR. Thanks!

**Comment by h2non** [comment]
Done! New version is available in `npm`. Thank you!
