### ISSUE TITLE
missing param password error

### ISSUE THREAD

**Issue by macquaries** [h2non/youtube-video-api#22]
i input password by parm but missing required param: password

where settings parm email,pw??

Show me examples in detail plz..

**Comment by h2non** [comment]
Use the GOOGLE_LOGIN_PASSWORD environment variable.

**Comment by macquaries** [comment]
thank you for commnet 

where is setting file?

**Comment by h2non** [comment]
You can pass the JSON file with the OAuth2 credentials via CLI using the `-f` flag:

``` bash
youtube-video-api upload -c clientId -s clientSecret -f config.json -v video.mp4
```
